version: "3.8"
services:
  web:
    image: ghcr.io/santaana/resume:latest
    command: sh -c '/app/bin/resume eval "Resume.Release.migrate" && /app/bin/server'
    ports: 
      - 4001:4001
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE} 
      PHX_HOST: ${PHX_HOST}
      ADMIN_USER: ${ADMIN_USER}
      VOYAGE_KEY: ${VOYAGE_KEY}
      LANGSEARCH_KEY: ${LANGSEARCH_KEY}
      OPENAI_KEY: ${OPENAI_KEY}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID}
    depends_on:
      - db
      - proxy
  db:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: resume
    ports: 
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
  proxy:
    image: caddy
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static:/srv
      - caddy_data:/data
      - caddy_config:/config
volumes:
  db:
    driver: local
  static:
  caddy_data: 
  caddy_config:
